[build]
  base    = "formik-examples/"
  command = "yarn build"
  publish = "formik-examples/build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200